/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import piratas.por.el.mundo.Esclavo;
import piratas.por.el.mundo.Isla;
import piratas.por.el.mundo.Isla2;
import piratas.por.el.mundo.Tesoro;

/**
 *
 * @author Tuxh
 */
public class VentanaIsla extends javax.swing.JFrame {

    /**
     * Creates new form VentanaIsla
     */
    Frame frame1;
    public VentanaIsla(Frame frame) {
        frame1 = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIsla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JtextNombreIsla = new javax.swing.JTextField();
        JtextTesoros = new javax.swing.JTextField();
        JtextPirataJefe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JtextEsclavos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JtextEstrellas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelIsla.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Isla"));
        panelIsla.setLayout(null);

        jLabel1.setText("Nombre Isla");
        panelIsla.add(jLabel1);
        jLabel1.setBounds(10, 30, 90, 14);

        jLabel2.setText("Número de Tesoros");
        panelIsla.add(jLabel2);
        jLabel2.setBounds(10, 60, 110, 14);

        jLabel3.setText("Pirata Jefe");
        panelIsla.add(jLabel3);
        jLabel3.setBounds(10, 90, 100, 14);

        JtextNombreIsla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextNombreIslaActionPerformed(evt);
            }
        });
        JtextNombreIsla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtextNombreIslaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtextNombreIslaKeyReleased(evt);
            }
        });
        panelIsla.add(JtextNombreIsla);
        JtextNombreIsla.setBounds(160, 30, 90, 20);

        JtextTesoros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtextTesorosKeyReleased(evt);
            }
        });
        panelIsla.add(JtextTesoros);
        JtextTesoros.setBounds(160, 60, 90, 20);

        JtextPirataJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextPirataJefeActionPerformed(evt);
            }
        });
        JtextPirataJefe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtextPirataJefeKeyReleased(evt);
            }
        });
        panelIsla.add(JtextPirataJefe);
        JtextPirataJefe.setBounds(160, 90, 90, 20);

        jLabel4.setText("Cantidad de Esclavos");
        panelIsla.add(jLabel4);
        jLabel4.setBounds(10, 120, 120, 14);

        JtextEsclavos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextEsclavosActionPerformed(evt);
            }
        });
        JtextEsclavos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtextEsclavosKeyReleased(evt);
            }
        });
        panelIsla.add(JtextEsclavos);
        JtextEsclavos.setBounds(160, 120, 90, 20);

        jLabel5.setText("Cantidad de Estrellas(1-5)");
        panelIsla.add(jLabel5);
        jLabel5.setBounds(10, 150, 130, 14);

        JtextEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextEstrellasActionPerformed(evt);
            }
        });
        JtextEstrellas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtextEstrellasKeyReleased(evt);
            }
        });
        panelIsla.add(JtextEstrellas);
        JtextEstrellas.setBounds(160, 150, 90, 20);

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelIsla, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIsla, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );

        panelIsla.getAccessibleContext().setAccessibleName("Nueva Isla");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtextNombreIslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextNombreIslaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextNombreIslaActionPerformed

    private void JtextNombreIslaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtextNombreIslaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextNombreIslaKeyPressed

    private void JtextNombreIslaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtextNombreIslaKeyReleased

    }//GEN-LAST:event_JtextNombreIslaKeyReleased

    private void JtextTesorosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtextTesorosKeyReleased

    }//GEN-LAST:event_JtextTesorosKeyReleased

    private void JtextPirataJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextPirataJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextPirataJefeActionPerformed

    private void JtextPirataJefeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtextPirataJefeKeyReleased

    }//GEN-LAST:event_JtextPirataJefeKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cantidadTesoros = Integer.parseInt(JtextEstrellas.getText());
        ArrayList<Tesoro> listaTesoros = new ArrayList<Tesoro>();
        for (int i = 0; i < cantidadTesoros; i++) {
            int fortunaTesoro = (int) Math.random() * 5 + 1;
            listaTesoros.add(new Tesoro(fortunaTesoro));
        }
        int cantidadEsclavos = Integer.parseInt(JtextEsclavos.getText());
        ArrayList<Esclavo> listaEsclavos = new ArrayList<Esclavo>();
        for (int i = 0; i < cantidadEsclavos; i++) {
            int edadEsclavo = (int) Math.random()*80 + 1;
            String edadEsclavo2 = "";
            if(edadEsclavo <= 30){
                edadEsclavo2 = "joven";
            }
            if(edadEsclavo > 30 && edadEsclavo <= 60){
                edadEsclavo2 = "adulto";
            }
            if(edadEsclavo > 60){
                edadEsclavo2 = "viejo";
            }
            listaEsclavos.add(new Esclavo(edadEsclavo2));
        }
        
        new Isla2(JtextNombreIsla.getText(), listaTesoros,
                JtextPirataJefe.getText(), listaEsclavos);
        
        frame1.setEnabled(true);
        this.setEnabled(false);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JtextEsclavosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextEsclavosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextEsclavosActionPerformed

    private void JtextEsclavosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtextEsclavosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextEsclavosKeyReleased

    private void JtextEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextEstrellasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextEstrellasActionPerformed

    private void JtextEstrellasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtextEstrellasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextEstrellasKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       frame1.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIsla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIsla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIsla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIsla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new VentanaIsla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtextEsclavos;
    private javax.swing.JTextField JtextEstrellas;
    private javax.swing.JTextField JtextNombreIsla;
    private javax.swing.JTextField JtextPirataJefe;
    private javax.swing.JTextField JtextTesoros;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelIsla;
    // End of variables declaration//GEN-END:variables
}
