//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BarcoEnemigo.java
//  @ Date : 29/06/2019
//  @ Author : 
//
//
package piratas.por.el.mundo;



public class BarcoEnemigo extends Barco {
	public int peligrosidad;

    public BarcoEnemigo(String nombreBarco, Pirata capitan, Esclavo[] cantEsclavos) {
        super(nombreBarco, capitan, cantEsclavos);
    }
}
