//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Continente.java
//  @ Date : 29/06/2019
//  @ Author : 
//
//
package piratas.por.el.mundo;



public class Continente {
	public String nombreContinente;
	public Isla[] islas;
	public Mostro[] Monstruo;
}
