package piratas.por.el.mundo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mostro.java
//  @ Date : 29/06/2019
//  @ Author : 
//
//




public class Mostro {
	public String tipo;
	public int poderDestructivo;
}
